
namespace MultiFaceRec
{
    partial class FrmPhong
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmPhong));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.txttinhtrang = new Bunifu.UI.WinForms.BunifuDropdown();
            this.dgvdata = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnxoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnsua = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnThem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtsearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtsonguoi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtgia = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtsophong = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtmaphong = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvdata)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuLabel6);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel5);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.txttinhtrang);
            this.bunifuPanel1.Controls.Add(this.dgvdata);
            this.bunifuPanel1.Controls.Add(this.btnxoa);
            this.bunifuPanel1.Controls.Add(this.btnsua);
            this.bunifuPanel1.Controls.Add(this.btnThem);
            this.bunifuPanel1.Controls.Add(this.txtsearch);
            this.bunifuPanel1.Controls.Add(this.txtsonguoi);
            this.bunifuPanel1.Controls.Add(this.txtgia);
            this.bunifuPanel1.Controls.Add(this.txtsophong);
            this.bunifuPanel1.Controls.Add(this.txtmaphong);
            this.bunifuPanel1.Location = new System.Drawing.Point(-1, -2);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1321, 798);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // txttinhtrang
            // 
            this.txttinhtrang.BackColor = System.Drawing.Color.Transparent;
            this.txttinhtrang.BackgroundColor = System.Drawing.Color.White;
            this.txttinhtrang.BorderColor = System.Drawing.Color.Silver;
            this.txttinhtrang.BorderRadius = 1;
            this.txttinhtrang.Color = System.Drawing.Color.Silver;
            this.txttinhtrang.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.txttinhtrang.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.txttinhtrang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txttinhtrang.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.txttinhtrang.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.txttinhtrang.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.txttinhtrang.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.txttinhtrang.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.txttinhtrang.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.txttinhtrang.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.txttinhtrang.FillDropDown = true;
            this.txttinhtrang.FillIndicator = false;
            this.txttinhtrang.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.txttinhtrang.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txttinhtrang.ForeColor = System.Drawing.Color.Black;
            this.txttinhtrang.FormattingEnabled = true;
            this.txttinhtrang.Icon = null;
            this.txttinhtrang.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.txttinhtrang.IndicatorColor = System.Drawing.Color.Gray;
            this.txttinhtrang.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.txttinhtrang.ItemBackColor = System.Drawing.Color.White;
            this.txttinhtrang.ItemBorderColor = System.Drawing.Color.White;
            this.txttinhtrang.ItemForeColor = System.Drawing.Color.Black;
            this.txttinhtrang.ItemHeight = 26;
            this.txttinhtrang.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.txttinhtrang.ItemHighLightForeColor = System.Drawing.Color.White;
            this.txttinhtrang.Items.AddRange(new object[] {
            "Cũ",
            "Mới"});
            this.txttinhtrang.ItemTopMargin = 3;
            this.txttinhtrang.Location = new System.Drawing.Point(407, 107);
            this.txttinhtrang.Margin = new System.Windows.Forms.Padding(4);
            this.txttinhtrang.Name = "txttinhtrang";
            this.txttinhtrang.Size = new System.Drawing.Size(243, 32);
            this.txttinhtrang.TabIndex = 113;
            this.txttinhtrang.Text = null;
            this.txttinhtrang.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.txttinhtrang.TextLeftMargin = 5;
            // 
            // dgvdata
            // 
            this.dgvdata.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dgvdata.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvdata.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dgvdata.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvdata.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvdata.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvdata.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvdata.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvdata.ColumnHeadersHeight = 40;
            this.dgvdata.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgvdata.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvdata.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvdata.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvdata.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvdata.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgvdata.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvdata.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgvdata.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvdata.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvdata.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgvdata.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvdata.CurrentTheme.Name = null;
            this.dgvdata.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgvdata.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvdata.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvdata.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvdata.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvdata.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvdata.EnableHeadersVisualStyles = false;
            this.dgvdata.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvdata.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgvdata.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvdata.HeaderForeColor = System.Drawing.Color.White;
            this.dgvdata.Location = new System.Drawing.Point(-3, 325);
            this.dgvdata.Name = "dgvdata";
            this.dgvdata.ReadOnly = true;
            this.dgvdata.RowHeadersVisible = false;
            this.dgvdata.RowHeadersWidth = 51;
            this.dgvdata.RowTemplate.Height = 40;
            this.dgvdata.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvdata.Size = new System.Drawing.Size(1324, 470);
            this.dgvdata.TabIndex = 19;
            this.dgvdata.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dgvdata.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvdata_CellContentClick);
            // 
            // btnxoa
            // 
            this.btnxoa.AllowAnimations = true;
            this.btnxoa.AllowMouseEffects = true;
            this.btnxoa.AllowToggling = false;
            this.btnxoa.AnimationSpeed = 200;
            this.btnxoa.AutoGenerateColors = false;
            this.btnxoa.AutoRoundBorders = false;
            this.btnxoa.AutoSizeLeftIcon = true;
            this.btnxoa.AutoSizeRightIcon = true;
            this.btnxoa.BackColor = System.Drawing.Color.Transparent;
            this.btnxoa.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnxoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnxoa.BackgroundImage")));
            this.btnxoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnxoa.ButtonText = "Xóa";
            this.btnxoa.ButtonTextMarginLeft = 0;
            this.btnxoa.ColorContrastOnClick = 45;
            this.btnxoa.ColorContrastOnHover = 45;
            this.btnxoa.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnxoa.CustomizableEdges = borderEdges1;
            this.btnxoa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnxoa.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnxoa.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnxoa.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnxoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnxoa.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnxoa.ForeColor = System.Drawing.Color.White;
            this.btnxoa.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnxoa.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnxoa.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnxoa.IconMarginLeft = 11;
            this.btnxoa.IconPadding = 10;
            this.btnxoa.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnxoa.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnxoa.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnxoa.IconSize = 25;
            this.btnxoa.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnxoa.IdleBorderRadius = 1;
            this.btnxoa.IdleBorderThickness = 1;
            this.btnxoa.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnxoa.IdleIconLeftImage = null;
            this.btnxoa.IdleIconRightImage = null;
            this.btnxoa.IndicateFocus = false;
            this.btnxoa.Location = new System.Drawing.Point(1149, 259);
            this.btnxoa.Name = "btnxoa";
            this.btnxoa.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnxoa.OnDisabledState.BorderRadius = 1;
            this.btnxoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnxoa.OnDisabledState.BorderThickness = 1;
            this.btnxoa.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnxoa.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnxoa.OnDisabledState.IconLeftImage = null;
            this.btnxoa.OnDisabledState.IconRightImage = null;
            this.btnxoa.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnxoa.onHoverState.BorderRadius = 1;
            this.btnxoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnxoa.onHoverState.BorderThickness = 1;
            this.btnxoa.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnxoa.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnxoa.onHoverState.IconLeftImage = null;
            this.btnxoa.onHoverState.IconRightImage = null;
            this.btnxoa.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnxoa.OnIdleState.BorderRadius = 1;
            this.btnxoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnxoa.OnIdleState.BorderThickness = 1;
            this.btnxoa.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnxoa.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnxoa.OnIdleState.IconLeftImage = null;
            this.btnxoa.OnIdleState.IconRightImage = null;
            this.btnxoa.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnxoa.OnPressedState.BorderRadius = 1;
            this.btnxoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnxoa.OnPressedState.BorderThickness = 1;
            this.btnxoa.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnxoa.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnxoa.OnPressedState.IconLeftImage = null;
            this.btnxoa.OnPressedState.IconRightImage = null;
            this.btnxoa.Size = new System.Drawing.Size(113, 39);
            this.btnxoa.TabIndex = 18;
            this.btnxoa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnxoa.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnxoa.TextMarginLeft = 0;
            this.btnxoa.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnxoa.UseDefaultRadiusAndThickness = true;
            this.btnxoa.Click += new System.EventHandler(this.btnxoa_Click);
            // 
            // btnsua
            // 
            this.btnsua.AllowAnimations = true;
            this.btnsua.AllowMouseEffects = true;
            this.btnsua.AllowToggling = false;
            this.btnsua.AnimationSpeed = 200;
            this.btnsua.AutoGenerateColors = false;
            this.btnsua.AutoRoundBorders = false;
            this.btnsua.AutoSizeLeftIcon = true;
            this.btnsua.AutoSizeRightIcon = true;
            this.btnsua.BackColor = System.Drawing.Color.Transparent;
            this.btnsua.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnsua.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnsua.BackgroundImage")));
            this.btnsua.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsua.ButtonText = "Sửa";
            this.btnsua.ButtonTextMarginLeft = 0;
            this.btnsua.ColorContrastOnClick = 45;
            this.btnsua.ColorContrastOnHover = 45;
            this.btnsua.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnsua.CustomizableEdges = borderEdges2;
            this.btnsua.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnsua.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsua.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsua.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsua.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnsua.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnsua.ForeColor = System.Drawing.Color.White;
            this.btnsua.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnsua.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnsua.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnsua.IconMarginLeft = 11;
            this.btnsua.IconPadding = 10;
            this.btnsua.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnsua.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnsua.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnsua.IconSize = 25;
            this.btnsua.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnsua.IdleBorderRadius = 1;
            this.btnsua.IdleBorderThickness = 1;
            this.btnsua.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnsua.IdleIconLeftImage = null;
            this.btnsua.IdleIconRightImage = null;
            this.btnsua.IndicateFocus = false;
            this.btnsua.Location = new System.Drawing.Point(979, 259);
            this.btnsua.Name = "btnsua";
            this.btnsua.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsua.OnDisabledState.BorderRadius = 1;
            this.btnsua.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsua.OnDisabledState.BorderThickness = 1;
            this.btnsua.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsua.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsua.OnDisabledState.IconLeftImage = null;
            this.btnsua.OnDisabledState.IconRightImage = null;
            this.btnsua.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnsua.onHoverState.BorderRadius = 1;
            this.btnsua.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsua.onHoverState.BorderThickness = 1;
            this.btnsua.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnsua.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnsua.onHoverState.IconLeftImage = null;
            this.btnsua.onHoverState.IconRightImage = null;
            this.btnsua.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnsua.OnIdleState.BorderRadius = 1;
            this.btnsua.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsua.OnIdleState.BorderThickness = 1;
            this.btnsua.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnsua.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnsua.OnIdleState.IconLeftImage = null;
            this.btnsua.OnIdleState.IconRightImage = null;
            this.btnsua.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnsua.OnPressedState.BorderRadius = 1;
            this.btnsua.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsua.OnPressedState.BorderThickness = 1;
            this.btnsua.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnsua.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnsua.OnPressedState.IconLeftImage = null;
            this.btnsua.OnPressedState.IconRightImage = null;
            this.btnsua.Size = new System.Drawing.Size(113, 39);
            this.btnsua.TabIndex = 17;
            this.btnsua.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnsua.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnsua.TextMarginLeft = 0;
            this.btnsua.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnsua.UseDefaultRadiusAndThickness = true;
            this.btnsua.Click += new System.EventHandler(this.btnsua_Click);
            // 
            // btnThem
            // 
            this.btnThem.AllowAnimations = true;
            this.btnThem.AllowMouseEffects = true;
            this.btnThem.AllowToggling = false;
            this.btnThem.AnimationSpeed = 200;
            this.btnThem.AutoGenerateColors = false;
            this.btnThem.AutoRoundBorders = false;
            this.btnThem.AutoSizeLeftIcon = true;
            this.btnThem.AutoSizeRightIcon = true;
            this.btnThem.BackColor = System.Drawing.Color.Transparent;
            this.btnThem.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnThem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThem.BackgroundImage")));
            this.btnThem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.ButtonText = "Thêm";
            this.btnThem.ButtonTextMarginLeft = 0;
            this.btnThem.ColorContrastOnClick = 45;
            this.btnThem.ColorContrastOnHover = 45;
            this.btnThem.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnThem.CustomizableEdges = borderEdges3;
            this.btnThem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThem.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnThem.ForeColor = System.Drawing.Color.White;
            this.btnThem.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThem.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnThem.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThem.IconMarginLeft = 11;
            this.btnThem.IconPadding = 10;
            this.btnThem.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThem.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnThem.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThem.IconSize = 25;
            this.btnThem.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnThem.IdleBorderRadius = 1;
            this.btnThem.IdleBorderThickness = 1;
            this.btnThem.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnThem.IdleIconLeftImage = null;
            this.btnThem.IdleIconRightImage = null;
            this.btnThem.IndicateFocus = false;
            this.btnThem.Location = new System.Drawing.Point(814, 259);
            this.btnThem.Name = "btnThem";
            this.btnThem.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThem.OnDisabledState.BorderRadius = 1;
            this.btnThem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnDisabledState.BorderThickness = 1;
            this.btnThem.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThem.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThem.OnDisabledState.IconLeftImage = null;
            this.btnThem.OnDisabledState.IconRightImage = null;
            this.btnThem.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnThem.onHoverState.BorderRadius = 1;
            this.btnThem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.onHoverState.BorderThickness = 1;
            this.btnThem.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnThem.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnThem.onHoverState.IconLeftImage = null;
            this.btnThem.onHoverState.IconRightImage = null;
            this.btnThem.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnThem.OnIdleState.BorderRadius = 1;
            this.btnThem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnIdleState.BorderThickness = 1;
            this.btnThem.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnThem.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnThem.OnIdleState.IconLeftImage = null;
            this.btnThem.OnIdleState.IconRightImage = null;
            this.btnThem.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThem.OnPressedState.BorderRadius = 1;
            this.btnThem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnPressedState.BorderThickness = 1;
            this.btnThem.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThem.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnThem.OnPressedState.IconLeftImage = null;
            this.btnThem.OnPressedState.IconRightImage = null;
            this.btnThem.Size = new System.Drawing.Size(113, 39);
            this.btnThem.TabIndex = 16;
            this.btnThem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThem.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThem.TextMarginLeft = 0;
            this.btnThem.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnThem.UseDefaultRadiusAndThickness = true;
            this.btnThem.Click += new System.EventHandler(this.btnThem_Click);
            // 
            // txtsearch
            // 
            this.txtsearch.AcceptsReturn = false;
            this.txtsearch.AcceptsTab = false;
            this.txtsearch.AnimationSpeed = 200;
            this.txtsearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtsearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtsearch.BackColor = System.Drawing.Color.Transparent;
            this.txtsearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtsearch.BackgroundImage")));
            this.txtsearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtsearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtsearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtsearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtsearch.BorderRadius = 1;
            this.txtsearch.BorderThickness = 1;
            this.txtsearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtsearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsearch.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtsearch.DefaultText = "";
            this.txtsearch.FillColor = System.Drawing.Color.White;
            this.txtsearch.HideSelection = true;
            this.txtsearch.IconLeft = null;
            this.txtsearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsearch.IconPadding = 10;
            this.txtsearch.IconRight = null;
            this.txtsearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsearch.Lines = new string[0];
            this.txtsearch.Location = new System.Drawing.Point(31, 259);
            this.txtsearch.MaxLength = 32767;
            this.txtsearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtsearch.Modified = false;
            this.txtsearch.Multiline = false;
            this.txtsearch.Name = "txtsearch";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtsearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsearch.OnIdleState = stateProperties4;
            this.txtsearch.Padding = new System.Windows.Forms.Padding(3);
            this.txtsearch.PasswordChar = '\0';
            this.txtsearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtsearch.PlaceholderText = "Search by iD";
            this.txtsearch.ReadOnly = false;
            this.txtsearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtsearch.SelectedText = "";
            this.txtsearch.SelectionLength = 0;
            this.txtsearch.SelectionStart = 0;
            this.txtsearch.ShortcutsEnabled = true;
            this.txtsearch.Size = new System.Drawing.Size(737, 41);
            this.txtsearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtsearch.TabIndex = 15;
            this.txtsearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtsearch.TextMarginBottom = 0;
            this.txtsearch.TextMarginLeft = 3;
            this.txtsearch.TextMarginTop = 0;
            this.txtsearch.TextPlaceholder = "Search by iD";
            this.txtsearch.UseSystemPasswordChar = false;
            this.txtsearch.WordWrap = true;
            this.txtsearch.TextChanged += new System.EventHandler(this.bunifuTextBox6_TextChanged);
            // 
            // txtsonguoi
            // 
            this.txtsonguoi.AcceptsReturn = false;
            this.txtsonguoi.AcceptsTab = false;
            this.txtsonguoi.AnimationSpeed = 200;
            this.txtsonguoi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtsonguoi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtsonguoi.BackColor = System.Drawing.Color.Transparent;
            this.txtsonguoi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtsonguoi.BackgroundImage")));
            this.txtsonguoi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtsonguoi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtsonguoi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtsonguoi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtsonguoi.BorderRadius = 1;
            this.txtsonguoi.BorderThickness = 1;
            this.txtsonguoi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtsonguoi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsonguoi.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtsonguoi.DefaultText = "";
            this.txtsonguoi.FillColor = System.Drawing.Color.White;
            this.txtsonguoi.HideSelection = true;
            this.txtsonguoi.IconLeft = null;
            this.txtsonguoi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsonguoi.IconPadding = 10;
            this.txtsonguoi.IconRight = null;
            this.txtsonguoi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsonguoi.Lines = new string[0];
            this.txtsonguoi.Location = new System.Drawing.Point(31, 107);
            this.txtsonguoi.MaxLength = 32767;
            this.txtsonguoi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtsonguoi.Modified = false;
            this.txtsonguoi.Multiline = false;
            this.txtsonguoi.Name = "txtsonguoi";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsonguoi.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtsonguoi.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsonguoi.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsonguoi.OnIdleState = stateProperties8;
            this.txtsonguoi.Padding = new System.Windows.Forms.Padding(3);
            this.txtsonguoi.PasswordChar = '\0';
            this.txtsonguoi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtsonguoi.PlaceholderText = "So Nguoi";
            this.txtsonguoi.ReadOnly = false;
            this.txtsonguoi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtsonguoi.SelectedText = "";
            this.txtsonguoi.SelectionLength = 0;
            this.txtsonguoi.SelectionStart = 0;
            this.txtsonguoi.ShortcutsEnabled = true;
            this.txtsonguoi.Size = new System.Drawing.Size(243, 41);
            this.txtsonguoi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtsonguoi.TabIndex = 14;
            this.txtsonguoi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtsonguoi.TextMarginBottom = 0;
            this.txtsonguoi.TextMarginLeft = 3;
            this.txtsonguoi.TextMarginTop = 0;
            this.txtsonguoi.TextPlaceholder = "So Nguoi";
            this.txtsonguoi.UseSystemPasswordChar = false;
            this.txtsonguoi.WordWrap = true;
            // 
            // txtgia
            // 
            this.txtgia.AcceptsReturn = false;
            this.txtgia.AcceptsTab = false;
            this.txtgia.AnimationSpeed = 200;
            this.txtgia.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtgia.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtgia.BackColor = System.Drawing.Color.Transparent;
            this.txtgia.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtgia.BackgroundImage")));
            this.txtgia.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtgia.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtgia.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtgia.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtgia.BorderRadius = 1;
            this.txtgia.BorderThickness = 1;
            this.txtgia.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtgia.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtgia.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtgia.DefaultText = "";
            this.txtgia.FillColor = System.Drawing.Color.White;
            this.txtgia.HideSelection = true;
            this.txtgia.IconLeft = null;
            this.txtgia.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtgia.IconPadding = 10;
            this.txtgia.IconRight = null;
            this.txtgia.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtgia.Lines = new string[0];
            this.txtgia.Location = new System.Drawing.Point(407, 29);
            this.txtgia.MaxLength = 32767;
            this.txtgia.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtgia.Modified = false;
            this.txtgia.Multiline = false;
            this.txtgia.Name = "txtgia";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtgia.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtgia.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtgia.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtgia.OnIdleState = stateProperties12;
            this.txtgia.Padding = new System.Windows.Forms.Padding(3);
            this.txtgia.PasswordChar = '\0';
            this.txtgia.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtgia.PlaceholderText = "Gia Phong";
            this.txtgia.ReadOnly = false;
            this.txtgia.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtgia.SelectedText = "";
            this.txtgia.SelectionLength = 0;
            this.txtgia.SelectionStart = 0;
            this.txtgia.ShortcutsEnabled = true;
            this.txtgia.Size = new System.Drawing.Size(243, 41);
            this.txtgia.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtgia.TabIndex = 13;
            this.txtgia.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtgia.TextMarginBottom = 0;
            this.txtgia.TextMarginLeft = 3;
            this.txtgia.TextMarginTop = 0;
            this.txtgia.TextPlaceholder = "Gia Phong";
            this.txtgia.UseSystemPasswordChar = false;
            this.txtgia.WordWrap = true;
            // 
            // txtsophong
            // 
            this.txtsophong.AcceptsReturn = false;
            this.txtsophong.AcceptsTab = false;
            this.txtsophong.AnimationSpeed = 200;
            this.txtsophong.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtsophong.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtsophong.BackColor = System.Drawing.Color.Transparent;
            this.txtsophong.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtsophong.BackgroundImage")));
            this.txtsophong.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtsophong.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtsophong.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtsophong.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtsophong.BorderRadius = 1;
            this.txtsophong.BorderThickness = 1;
            this.txtsophong.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtsophong.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsophong.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtsophong.DefaultText = "";
            this.txtsophong.FillColor = System.Drawing.Color.White;
            this.txtsophong.HideSelection = true;
            this.txtsophong.IconLeft = null;
            this.txtsophong.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsophong.IconPadding = 10;
            this.txtsophong.IconRight = null;
            this.txtsophong.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsophong.Lines = new string[0];
            this.txtsophong.Location = new System.Drawing.Point(31, 189);
            this.txtsophong.MaxLength = 32767;
            this.txtsophong.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtsophong.Modified = false;
            this.txtsophong.Multiline = false;
            this.txtsophong.Name = "txtsophong";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsophong.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtsophong.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsophong.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsophong.OnIdleState = stateProperties16;
            this.txtsophong.Padding = new System.Windows.Forms.Padding(3);
            this.txtsophong.PasswordChar = '\0';
            this.txtsophong.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtsophong.PlaceholderText = "Số Phòng";
            this.txtsophong.ReadOnly = false;
            this.txtsophong.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtsophong.SelectedText = "";
            this.txtsophong.SelectionLength = 0;
            this.txtsophong.SelectionStart = 0;
            this.txtsophong.ShortcutsEnabled = true;
            this.txtsophong.Size = new System.Drawing.Size(243, 41);
            this.txtsophong.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtsophong.TabIndex = 11;
            this.txtsophong.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtsophong.TextMarginBottom = 0;
            this.txtsophong.TextMarginLeft = 3;
            this.txtsophong.TextMarginTop = 0;
            this.txtsophong.TextPlaceholder = "Số Phòng";
            this.txtsophong.UseSystemPasswordChar = false;
            this.txtsophong.WordWrap = true;
            // 
            // txtmaphong
            // 
            this.txtmaphong.AcceptsReturn = false;
            this.txtmaphong.AcceptsTab = false;
            this.txtmaphong.AnimationSpeed = 200;
            this.txtmaphong.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtmaphong.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtmaphong.BackColor = System.Drawing.Color.Transparent;
            this.txtmaphong.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtmaphong.BackgroundImage")));
            this.txtmaphong.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtmaphong.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtmaphong.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtmaphong.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtmaphong.BorderRadius = 1;
            this.txtmaphong.BorderThickness = 1;
            this.txtmaphong.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtmaphong.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtmaphong.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtmaphong.DefaultText = "";
            this.txtmaphong.FillColor = System.Drawing.Color.White;
            this.txtmaphong.HideSelection = true;
            this.txtmaphong.IconLeft = null;
            this.txtmaphong.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtmaphong.IconPadding = 10;
            this.txtmaphong.IconRight = null;
            this.txtmaphong.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtmaphong.Lines = new string[0];
            this.txtmaphong.Location = new System.Drawing.Point(31, 29);
            this.txtmaphong.MaxLength = 32767;
            this.txtmaphong.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtmaphong.Modified = false;
            this.txtmaphong.Multiline = false;
            this.txtmaphong.Name = "txtmaphong";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmaphong.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtmaphong.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmaphong.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmaphong.OnIdleState = stateProperties20;
            this.txtmaphong.Padding = new System.Windows.Forms.Padding(3);
            this.txtmaphong.PasswordChar = '\0';
            this.txtmaphong.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtmaphong.PlaceholderText = "Ma Phong";
            this.txtmaphong.ReadOnly = false;
            this.txtmaphong.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtmaphong.SelectedText = "";
            this.txtmaphong.SelectionLength = 0;
            this.txtmaphong.SelectionStart = 0;
            this.txtmaphong.ShortcutsEnabled = true;
            this.txtmaphong.Size = new System.Drawing.Size(243, 41);
            this.txtmaphong.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtmaphong.TabIndex = 10;
            this.txtmaphong.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtmaphong.TextMarginBottom = 0;
            this.txtmaphong.TextMarginLeft = 3;
            this.txtmaphong.TextMarginTop = 0;
            this.txtmaphong.TextPlaceholder = "Ma Phong";
            this.txtmaphong.UseSystemPasswordChar = false;
            this.txtmaphong.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(31, 3);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(67, 20);
            this.bunifuLabel1.TabIndex = 114;
            this.bunifuLabel1.Text = "Mã Phòng";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(31, 81);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(60, 20);
            this.bunifuLabel2.TabIndex = 115;
            this.bunifuLabel2.Text = "Số người";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(31, 163);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(63, 20);
            this.bunifuLabel3.TabIndex = 116;
            this.bunifuLabel3.Text = "Số Phòng";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(31, 233);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(63, 20);
            this.bunifuLabel4.TabIndex = 117;
            this.bunifuLabel4.Text = "Tìm Kiếm";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel5.Location = new System.Drawing.Point(407, 76);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(68, 20);
            this.bunifuLabel5.TabIndex = 118;
            this.bunifuLabel5.Text = "Mã phòng";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel6.Location = new System.Drawing.Point(407, 0);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(68, 20);
            this.bunifuLabel6.TabIndex = 119;
            this.bunifuLabel6.Text = "Gía Phòng";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // FrmPhong
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1318, 787);
            this.Controls.Add(this.bunifuPanel1);
            this.Name = "FrmPhong";
            this.Text = "FrmPhong";
            this.Load += new System.EventHandler(this.FrmPhong_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvdata)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvdata;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnxoa;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnsua;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThem;
        private Bunifu.UI.WinForms.BunifuTextBox txtsearch;
        private Bunifu.UI.WinForms.BunifuTextBox txtsonguoi;
        private Bunifu.UI.WinForms.BunifuTextBox txtgia;
        private Bunifu.UI.WinForms.BunifuTextBox txtsophong;
        private Bunifu.UI.WinForms.BunifuTextBox txtmaphong;
        private Bunifu.UI.WinForms.BunifuDropdown txttinhtrang;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
    }
}